##
## Common
##
fullname: asm-webhook
namespace: default

##
## Webhook
##
webhookLabels:
  app: asm-webhook
webhookSelectorLabels: # Labels of pods to be mutated
  asm-webhook: "true"
caBundle: # execute generate.sh script

##
## Service
##
serviceLabels:
  app: asm-webhook

serviceSelectorLabels:
  app: asm-webhook

##
## ServiceAccount
##
serviceAccountName: webhook
roleArn: # "arn:aws:iam::111111111111:role/webhook". Enter random value if on minikube. This role is only used to occasionaly fetch config images when the command argument is missing from a container description

##
## Deployment
##
replicaCount: 1
image: ayoul3/asm-webhook
command: /app/asm-webhook
pullPolicy: Always
deploymentLabels:
  app: asm-webhook
deploymentMatchLabels:
  app: asm-webhook
podAnnotations: {}

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
