##
## Common
##
fullname: asm-webhook
namespace: default

##
## Webhook
##
webhookLabels:
  app: asm-webhook
webhookSelectorLabels: # Labels of pods to be mutated
  asm-webhook: "true"
caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJd01ESXlNVEE1TWpJd09Gb1hEVE13TURJeE9UQTVNakl3T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTB1CjdlVm1PVWJ1NkJmRmFvUllsS0VOOFNxTERVQXp0di9kRTB4Q0RMUzk0UXdraHU0NU9rZktXZXBicisxeEFhT0kKVWFzdXV3WVZudHRXK211R1VYYWdzUyswMTc2NG9zdDFRNGRVOGo4dDNDRHYwYXV4N2FFUThsTU1aRkdMZnVqTgpMdnZCcmsxc3FoNDZWOW5FUWJCTXJkNlpCTzJZSTJWNk01RVkxZnFMek5GZmJUR2xUbG5ZYWhtZkc2TFBHQ1Q0CnZtTStOcEFnYTlVL05IVkw5ZDdzMUJOaklGSzVQUGcrMlZrenZEdThCeTlrZVpIT041RXp3a3dGUG0vaUxXeUQKdS9Da2orRFk5NlVoZGhYMWJsZldVeXJMck1BRnkzUTBNbDU3dS81cm5ZOFhQSCt5UGtUdGtZcU1ScHp4NSsxRAo5b1FZQjZ2WDBGUmJiTmYwWnE4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCWjRaN2c2Y1pqa1lBSGhDdlMxSVVEZlJ3MnJxNlUrZ2pXQkM2eThaeE53QitmYzhxTgp6emQxT1grWHRJc2M3LzRTZmd1a1RGRHdBYmxkbnBtUzJ3aWFEa01GNXlHU2M2RGExTXU1VG5zOXNpbFdJQWhJCmMzWTZuaTQwbWs4WFZBd2E3YklMVWlXeCtJWWt1QnFVUTNpck54aWxPZWQ5SHpvalI2SkZsUnA3cjJWb2RWN2MKczE1aW9aRW5sNGRqR0hmZXk1dlBlQ0V0aXd0bXh0K0plV1lwWCtjb3gxaTUxYXAzT1BoQTg5MU1ZVk9HamNTUQpjTllaL0RKeURLbWllajNjQkxPVlZSbmMvL01XOWJmMSt4ODU3azZTWTBsd2tzMnZrMnJ3S3FTbmM1bEFVZlFvCm16R1pzTDNEbUZILzZxeFJSdVVwRGlkcTJOTXB3WGVRN25IWgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
#caBundleererer: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJd01ESXlNVEE1TWpJd09Gb1hEVE13TURJeE9UQTVNakl3T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTTB1CjdlVm1PVWJ1NkJmRmFvUllsS0VOOFNxTERVQXp0di9kRTB4Q0RMUzk0UXdraHU0NU9rZktXZXBicisxeEFhT0kKVWFzdXV3WVZudHRXK211R1VYYWdzUyswMTc2NG9zdDFRNGRVOGo4dDNDRHYwYXV4N2FFUThsTU1aRkdMZnVqTgpMdnZCcmsxc3FoNDZWOW5FUWJCTXJkNlpCTzJZSTJWNk01RVkxZnFMek5GZmJUR2xUbG5ZYWhtZkc2TFBHQ1Q0CnZtTStOcEFnYTlVL05IVkw5ZDdzMUJOaklGSzVQUGcrMlZrenZEdThCeTlrZVpIT041RXp3a3dGUG0vaUxXeUQKdS9Da2orRFk5NlVoZGhYMWJsZldVeXJMck1BRnkzUTBNbDU3dS81cm5ZOFhQSCt5UGtUdGtZcU1ScHp4NSsxRAo5b1FZQjZ2WDBGUmJiTmYwWnE4Q0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFCWjRaN2c2Y1pqa1lBSGhDdlMxSVVEZlJ3MnJxNlUrZ2pXQkM2eThaeE53QitmYzhxTgp6emQxT1grWHRJc2M3LzRTZmd1a1RGRHdBYmxkbnBtUzJ3aWFEa01GNXlHU2M2RGExTXU1VG5zOXNpbFdJQWhJCmMzWTZuaTQwbWs4WFZBd2E3YklMVWlXeCtJWWt1QnFVUTNpck54aWxPZWQ5SHpvalI2SkZsUnA3cjJWb2RWN2MKczE1aW9aRW5sNGRqR0hmZXk1dlBlQ0V0aXd0bXh0K0plV1lwWCtjb3gxaTUxYXAzT1BoQTg5MU1ZVk9HamNTUQpjTllaL0RKeURLbWllajNjQkxPVlZSbmMvL01XOWJmMSt4ODU3azZTWTBsd2tzMnZrMnJ3S3FTbmM1bEFVZlFvCm16R1pzTDNEbUZILzZxeFJSdVVwRGlkcTJOTXB3WGVRN25IWgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==


##
## Service
##
serviceLabels:
  app: asm-webhook

serviceSelectorLabels:
  app: asm-webhook

##
## ServiceAccount
##
serviceAccountName: asm-webhook
roleArn: "arn:aws:iam::<AWS_ACCOUNT_ID>:role/<IAM_ROLE_NAME>"

##
## Deployment
##
replicaCount: 1
image: ayoul3/asm-webhook
command: /app/asm-webhook
pullPolicy: Always
deploymentLabels:
  app: asm-webhook
deploymentMatchLabels:
  app: asm-webhook
podAnnotations: {}

resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 250m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
