---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fullname }}
  {{- with .Values.deploymentLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    {{- with .Values.deploymentMatchLabels }}
    matchLabels:
      {{- toYaml . | nindent 8 }}
    {{- end }}
  template:
    metadata:
      name: {{ .Values.fullname }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.deploymentLabels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: mutator
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.pullPolicy }}
          command:
            - {{ .Values.command }}
          args:
            - -tls-crt=/etc/webhook/certs/cert.pem
            - -tls-key=/etc/webhook/certs/key.pem
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ printf "%s-certs" .Values.fullname }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}