---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullname  }}
  {{- with .Values.serviceLabels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: {{ .Values.namespace }}
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 8443
  {{- with .Values.serviceSelectorLabels }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
