apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "ARN role for the webhook pod. See Readme  ##Prerequisites for more details" .Values.roleArn }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - serviceaccounts
    verbs:
      - "get"
      - "list"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.fullname }}
  namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: {{ .Values.fullname }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.namespace }}
  name: {{ .Values.serviceAccountName }}